version: '3.9'

# Development-specific overrides
# This file is automatically loaded by docker compose
services:
  backend:
    environment:
      - NODE_ENV=development
      - DEBUG=swrpg:*
    volumes:
      - ./src/backend:/app
      - /app/node_modules

  frontend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/frontend:/app
      - /app/node_modules